rules:
  # already following SAP policies
  dependabot-cooldown:
    config:
      days: 4
  dangerous-triggers:
    ignore:
      - dependabot-pnpm-lock.yml
      - lint-pr.yml # TODO: investigate if this really needs pull_request_target
  # allow unpinned references to own repositories
  unpinned-uses:
    config:
      policies:
        'sap/ai-sdk-js/*': any
        'sap/cloud-sdk-js/*': any
