name: setup
description: Setup repo, node and pnpm.
inputs:
  node-version:
    description: 'Node.js version'
    default: '20'
  pnpm-version:
    description: 'PNPM version'
    default: '9'
  ref:
    description: 'The GitHub ref to checkout'
    default: ${{ github.ref }}
  token:
    description: 'The GitHub token to use for checkout'
    default: ${{ github.token }}
  pnpm-install-args:
    description: 'Arguments to pass to pnpm install'
    default: '--frozen-lockfile'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
    - uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm-version }}
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - run: pnpm install ${{ pnpm-install-args }}
      shell: bash
