name: setup
description: Setup repo, node and pnpm.
inputs:
  node-version:
    description: 'Node.js version'
    default: '20'
  pnpm-version:
    description: 'PNPM version'
    default: '9'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v3
      with:
        version: ${{ inputs.pnpm-version }}
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
    - run: pnpm i --frozen-lockfile
      shell: bash
