packages:
  - packages/ai-api
  - packages/core
  - packages/document-grounding
  - packages/foundation-models
  - packages/openai
  - packages/langchain
  - packages/orchestration
  - packages/llm-batch
  - packages/prompt-registry
  - packages/rpt
  - sample-cap
  - sample-code
  - tests/e2e-tests
  - tests/smoke-tests
  - tests/type-tests

catalog:
  '@sap-cloud-sdk/connectivity': ^4.8.0
  '@sap-cloud-sdk/generator-common': ^4.8.0
  '@sap-cloud-sdk/http-client': ^4.8.0
  '@sap-cloud-sdk/openapi': ^4.8.0
  '@sap-cloud-sdk/openapi-generator': ^4.8.0
  '@sap-cloud-sdk/resilience': ^4.8.0
  '@sap-cloud-sdk/util': ^4.8.0
  '@langchain/core': ^1.2.4
  '@langchain/langgraph': ^1.4.8
  zod: ^4.4.3

allowBuilds:
  '@swc/core': true
  better-sqlite3: false
  esbuild: false
  unrs-resolver: false

blockExoticSubdeps: true
minimumReleaseAge: 5760
minimumReleaseAgeExclude:
  - '@sap-ai-sdk/*'
  - '@sap-cloud-sdk/*'
  - 'hono@4.12.34'
  # Add minimum age exceptions for audit issues here
  # - sample-package@0.1.0
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - 'picomatch@4.0.5'
trustPolicyIgnoreAfter: 131400 # 3 months
