packages:
  # all packages in direct subdirs of packages/
  - 'packages/ai-api'
  - 'packages/foundation-models'
  - 'packages/orchestration'
  - 'packages/core'
  - 'packages/langchain'
  - 'sample-code'
  - 'tests/e2e-tests'
  - 'tests/type-tests'
  - 'tests/smoke-tests'
  - 'tests/schema-tests'
