packages:
  # all packages in direct subdirs of packages/
  - 'packages/ai-core'
  - 'packages/gen-ai-hub'
  - 'packages/core'
  - 'sample-code'
  - 'tests/e2e-tests'
  - 'tests/type-tests'
  - 'tests/smoke-tests'
