packages:
  # all packages in direct subdirs of packages/
  - 'packages/ai-core'
  - 'packages/gen-ai-hub'
  # sample code
  - 'sample-code'
  # exclude packages that are inside test directories
  - '!poc/'
  - '!test-util'
  - '!type-tests/'
