packages:
  - packages/ai-api
  - packages/core
  - packages/document-grounding
  - packages/foundation-models
  - packages/langchain
  - packages/orchestration
  - packages/prompt-registry
  - packages/rpt
  - sample-cap
  - sample-code
  - tests/e2e-tests
  - tests/smoke-tests
  - tests/type-tests
