packages:
  # all packages in direct subdirs of packages/
  - 'packages/ai-core'
  - 'packages/gen-ai-hub'
  # sample code
  - 'sample-code'
  # exclude packages that are inside test directories
  - '!tests/e2e-tests' # including the e2e tests makes causes pnpm to explode
  - '!poc/'
  - '!test-util'
  - '!tests/type-tests'
