sonar.projectKey=SAP_ai-sdk-js
sonar.organization=sap-1

sonar.projectName=ai-sdk-js
sonar.links.homepage=https://sap.github.io/ai-sdk/docs/js/overview-cloud-sdk-for-ai-js
sonar.links.scm=https://github.com/sap/ai-sdk-js
sonar.links.issue=https://github.com/sap/ai-sdk-js/issues
sonar.links.ci=https://github.com/sap/ai-sdk-js/actions

sonar.sources=.
sonar.tests=\
  tests,\
  test-util
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/dist-cjs/**\,
  sample-code/resources/**
sonar.test.inclusions=**/*.test.ts

sonar.javascript.lcov.reportPaths=packages/**/coverage/lcov.info
sonar.coverage.exclusions=\
  **/sample-cap/**,\
  **/sample-code/**,\
  **/scripts/**,\
  **/client/**,\
  **/*.yml,\
  **/*.yaml,\
  **/*.json,\
  **/*.py, \
  **/*.d.ts
