name: 'Merge Changelogs'
description: 'Merges all public changelogs from changesets into a single changelog.'
runs:
  using: 'composite'
  steps:
    - name: Run merge-and-write-changelogs
      shell: bash
      working-directory: ${{ github.workspace }}/build-packages/merge-and-write-changelogs
      run: node index.ts
