const config = {
  prompt_registry: {
    output: {
      client: 'zod',
      mode: 'single',
      target: './src/zod/prompt-registry.zod.ts',
      override: {
        header: info => [
          `Generated by orval 🍺`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : [])
        ]
      }
    },
    input: {
      target: './src/spec/prompt-registry.yaml',
      validation: false
    }
  }
};

export default config;
