// Generated by ts-to-zod
import { z } from 'zod';

const azureOpenAiChatCompletionsResponseCommonSchema = z.any();

const azureOpenAiPromptFilterResultsSchema = z.any();

const azureOpenAiChatCompletionChoiceCommonSchema = z.any();

const azureOpenAiChatCompletionResponseMessageSchema = z.any();

const azureOpenAiContentFilterChoiceResultsSchema = z.any();

const azureOpenAiChatCompletionChoiceLogProbsSchema = z.any();

/**
 * @internal
 */
export const azureOpenAiCreateChatCompletionResponseSchema =
  azureOpenAiChatCompletionsResponseCommonSchema
    .and(
      z.object({
        prompt_filter_results: azureOpenAiPromptFilterResultsSchema.optional(),
        choices: z.array(
          azureOpenAiChatCompletionChoiceCommonSchema
            .and(
              z.object({
                message:
                  azureOpenAiChatCompletionResponseMessageSchema.optional(),
                content_filter_results:
                  azureOpenAiContentFilterChoiceResultsSchema.optional(),
                logprobs:
                  azureOpenAiChatCompletionChoiceLogProbsSchema.optional()
              })
            )
            .and(z.record(z.any()))
        )
      })
    )
    .and(z.record(z.any()));
