name: Bug Report
description: Released feature does not work as expected in the SAP Cloud SDK for AI (JavaScript / TypeScript).
title: '<title>'
labels: 
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please note that this repository is for JS/TS and SDK related issues only.
        Issue for SAP Cloud SDK for AI (Java), please open [here](https://github.com/SAP/ai-sdk-java/issues/new/choose).
        Issue for SAP AI Core services (Orchestration, Grounding, Prompt Registry, ...), please refer to the [SAP AI Core Support Process](https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/support-process).
  - type: checkboxes
    attributes:
      label: "Checklist"
      description: "Before submitting your issue, please make sure to check the following:"
      options:
        - label: "My issue is not an [AI Core service issue](https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/support-process), but an SDK issue."
          required: true
        - label: "My issue is a JS/TS related issue, not a [Java related issue](https://github.com/SAP/ai-sdk-java/issues)."
          required: true
        - label: "My issue is not [already reported or documented](https://github.com/SAP/ai-sdk-js/issues)."
          required: true
  - type: textarea
    attributes:
      label: "Describe the Bug"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Set up ...
        2. Execute ...
        3. Confirm ...
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Screenshots"
      description: "Add screenshots to help explain your problem."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Used Versions"
      description: "Provide versions used in the project."
      value: |
        - Node version via `node -v`: ...
        - NPM version via `npm -v: ...
        - SAP Cloud SDK for AI version:
          - ...
          - ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Code Examples"
      description: "Add code snippets as examples to help explain your problem. Please remove sensitive information."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Log File"
      description: "Add your log file or related error message. Again, please remove sensitive information."
    validations:
      required: false
  - type: dropdown
    attributes:
      label: "Region"
      description: "Choose the region of your AI Core service."
      multiple: true
      options:
        - AP10
        - EU10 Canary
        - EU10
        - EU11
        - EU12 Canary
        - EU20
        - EU30
        - JP10
        - US10
        - US21
        - US30
        - SA30
        - Not listed above
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Affected Development Phase"
      description: "Choose the development phase affected by this issue."
      multiple: false
      options:
        - Getting Started
        - Development
        - Release
        - Production
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Impact"
      description: "Choose the impact severity."
      multiple: false
      options:
        - No Impact
        - Inconvenience
        - Impaired
        - Blocked
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Timeline"
      description: "Please briefly state your timeline, e.g., Go-Live in 12 weeks."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
    validations:
      required: false
