// Generated by ts-to-zod
import { z } from 'zod';

/**
 * @internal
 */
export const azureOpenAiEmbeddingParametersSchema = z.object({
  input: z.union([z.array(z.string()), z.string()]),
  user: z.string().optional()
});

/**
 * @internal
 */
export const azureOpenAiEmbeddingOutputSchema = z.object({
  object: z.literal('list'),
  model: z.string(),
  data: z.tuple([
    z.object({
      object: z.literal('embedding'),
      embedding: z.array(z.number()),
      index: z.number()
    })
  ]),
  usage: z.object({
    prompt_tokens: z.number(),
    total_tokens: z.number()
  })
});
