// Generated by ts-to-zod
import { z } from 'zod';

import { functionObjectSchema } from './function-object.zod';

export const chatCompletionToolSchema = z.object({
  type: z.literal('function'),
  function: functionObjectSchema
});
