// Generated by ts-to-zod
import { z } from 'zod';

import { imageContentSchema } from './image-content.zod';
import { textContentSchema } from './text-content.zod';

export const multiChatContentSchema = z.union([
  imageContentSchema,
  textContentSchema
]);
