// Generated by ts-to-zod
import { z } from 'zod';
import { imageContentSchema } from './image-content.zod.js';
import { textContentSchema } from './text-content.zod.js';

/**
 * @internal
 **/
export const multiChatContentSchema = z.union([
  imageContentSchema,
  textContentSchema
]);
