/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Prompt Registry API
 * Prompt Storage service for Design time & Runtime prompt templates.
 * OpenAPI spec version: 0.0.1
 */
import * as zod from 'zod';

/**
 * Create or update a prompt template
 */
export const RegistryControllerPromptControllerCreateUpdatePromptTemplateHeader = zod.object({
  "AI-Resource-Group": zod.string().optional().describe('Specify a resource group id to use'),
  "AI-Resource-Group-Scope": zod.enum(['true', 'True', 'false', 'False']).optional().describe('Specify whether the resource group scope is to be used')
})

export const registryControllerPromptControllerCreateUpdatePromptTemplateBodyNameMax = 120;


export const registryControllerPromptControllerCreateUpdatePromptTemplateBodyNameRegExp = new RegExp('^[a-zA-Z0-9_-]+$');
export const registryControllerPromptControllerCreateUpdatePromptTemplateBodyVersionMax = 10;


export const registryControllerPromptControllerCreateUpdatePromptTemplateBodyVersionRegExp = new RegExp('^[a-zA-Z0-9._-]+$');
export const registryControllerPromptControllerCreateUpdatePromptTemplateBodyScenarioMax = 120;


export const registryControllerPromptControllerCreateUpdatePromptTemplateBodyScenarioRegExp = new RegExp('^[a-zA-Z0-9_-]+$');
export const registryControllerPromptControllerCreateUpdatePromptTemplateBodySpecTemplateItemTwoContentItemOneImageUrlDetailDefault = `auto`;
export const registryControllerPromptControllerCreateUpdatePromptTemplateBodySpecResponseFormatThreeJsonSchemaNameMax = 64;


export const registryControllerPromptControllerCreateUpdatePromptTemplateBodySpecResponseFormatThreeJsonSchemaNameRegExp = new RegExp('^[a-zA-Z0-9-_]+$');
export const registryControllerPromptControllerCreateUpdatePromptTemplateBodySpecResponseFormatThreeJsonSchemaStrictDefault = false;
export const registryControllerPromptControllerCreateUpdatePromptTemplateBodySpecToolsItemFunctionNameMax = 64;


export const registryControllerPromptControllerCreateUpdatePromptTemplateBodySpecToolsItemFunctionNameRegExp = new RegExp('^[a-zA-Z0-9-_]+$');
export const registryControllerPromptControllerCreateUpdatePromptTemplateBodySpecToolsItemFunctionStrictDefault = false;

export const RegistryControllerPromptControllerCreateUpdatePromptTemplateBody = zod.object({
  "name": zod.string().max(registryControllerPromptControllerCreateUpdatePromptTemplateBodyNameMax).regex(registryControllerPromptControllerCreateUpdatePromptTemplateBodyNameRegExp),
  "version": zod.string().max(registryControllerPromptControllerCreateUpdatePromptTemplateBodyVersionMax).regex(registryControllerPromptControllerCreateUpdatePromptTemplateBodyVersionRegExp),
  "scenario": zod.string().max(registryControllerPromptControllerCreateUpdatePromptTemplateBodyScenarioMax).regex(registryControllerPromptControllerCreateUpdatePromptTemplateBodyScenarioRegExp),
  "spec": zod.object({
  "template": zod.array(zod.union([zod.object({
  "role": zod.string(),
  "content": zod.string()
}),zod.object({
  "role": zod.string(),
  "content": zod.array(zod.union([zod.object({
  "type": zod.enum(['image_url']),
  "image_url": zod.object({
  "url": zod.string(),
  "detail": zod.string().default(registryControllerPromptControllerCreateUpdatePromptTemplateBodySpecTemplateItemTwoContentItemOneImageUrlDetailDefault)
})
}),zod.object({
  "type": zod.enum(['text']),
  "text": zod.string()
})]))
})])),
  "defaults": zod.looseObject({

}).optional(),
  "additionalFields": zod.looseObject({

}).optional().describe('DEPRECATED. Please use additional_fields instead.\n'),
  "response_format": zod.union([zod.object({
  "type": zod.enum(['text']).describe('The type of response format being defined: `text`')
}),zod.object({
  "type": zod.enum(['json_object']).describe('The type of response format being defined: `json_object`')
}),zod.object({
  "type": zod.enum(['json_schema']).describe('The type of response format being defined: `json_schema`'),
  "json_schema": zod.object({
  "description": zod.string().optional().describe('A description of what the response format is for, used by the model to determine how to respond in the format.'),
  "name": zod.string().max(registryControllerPromptControllerCreateUpdatePromptTemplateBodySpecResponseFormatThreeJsonSchemaNameMax).regex(registryControllerPromptControllerCreateUpdatePromptTemplateBodySpecResponseFormatThreeJsonSchemaNameRegExp).describe('The name of the response format. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.'),
  "schema": zod.record(zod.string(), zod.unknown()).optional().describe('The schema for the response format, described as a JSON Schema object.'),
  "strict": zod.boolean().nullish().default(registryControllerPromptControllerCreateUpdatePromptTemplateBodySpecResponseFormatThreeJsonSchemaStrictDefault).describe('Whether to enable strict schema adherence when generating the output. If set to true, the model will always follow the exact schema defined in the `schema` field. Only a subset of JSON Schema is supported when `strict` is `true`. To learn more, read the [Structured Outputs guide](https://platform.openai.com/docs/guides/structured-outputs).')
})
})]).optional().describe('Response format that the model output should adhere to. This is the same as the OpenAI definition.\nCompatible with GPT-4o, GPT-4o mini, GPT-4 (Turbo) and all GPT-3.5 Turbo models newer than gpt-3.5-turbo-1106.\n'),
  "tools": zod.array(zod.object({
  "type": zod.enum(['function']).describe('The type of the tool. Currently, only `function` is supported.'),
  "function": zod.object({
  "description": zod.string().optional().describe('A description of what the function does, used by the model to choose when and how to call the function.'),
  "name": zod.string().max(registryControllerPromptControllerCreateUpdatePromptTemplateBodySpecToolsItemFunctionNameMax).regex(registryControllerPromptControllerCreateUpdatePromptTemplateBodySpecToolsItemFunctionNameRegExp).describe('The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.'),
  "parameters": zod.record(zod.string(), zod.unknown()).optional().describe('The parameters the functions accepts, described as a JSON Schema object. See the [guide](https://platform.openai.com/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format.  Omitting `parameters` defines a function with an empty parameter list.'),
  "strict": zod.boolean().nullish().default(registryControllerPromptControllerCreateUpdatePromptTemplateBodySpecToolsItemFunctionStrictDefault).describe('Whether to enable strict schema adherence when generating the function call. If set to true, the model will follow the exact schema defined in the `parameters` field. Only a subset of JSON Schema is supported when `strict` is `true`. Learn more about Structured Outputs in the [function calling guide](docs/guides/function-calling).')
})
})).optional().describe('A list of tools the model may call. Used to provide a list of functions the model may generate JSON inputs for. This is the same as the OpenAI definition.\n')
})
})

export const RegistryControllerPromptControllerCreateUpdatePromptTemplateResponse = zod.object({
  "message": zod.string(),
  "id": zod.uuid(),
  "scenario": zod.string(),
  "name": zod.string(),
  "version": zod.string()
})
