// Generated by ts-to-zod
import { z } from 'zod';
import { promptTemplateSpecSchema } from './prompt-template-spec.zod.js';

/**
 * @internal
 **/
export const promptTemplatePostRequestSchema = z
  .object({
    name: z.string(),
    version: z.string(),
    scenario: z.string(),
    spec: promptTemplateSpecSchema
  })
  .and(z.record(z.any()));
