// Generated by ts-to-zod
import { z } from 'zod';

import { templateSchema } from './template.zod';
import { responseFormatTextSchema } from './response-format-text.zod';
import { responseFormatJsonObjectSchema } from './response-format-json-object.zod';
import { responseFormatJsonSchemaSchema } from './response-format-json-schema.zod';
import { chatCompletionToolSchema } from './chat-completion-tool.zod';

export const promptTemplateSpecSchema = z
  .object({
    template: z.array(templateSchema),
    defaults: z.record(z.any()).optional(),
    additionalFields: z.record(z.any()).optional(),
    response_format: z
      .union([
        responseFormatTextSchema,
        responseFormatJsonObjectSchema,
        responseFormatJsonSchemaSchema
      ])
      .optional(),
    tools: z.array(chatCompletionToolSchema).optional()
  })
  .and(z.record(z.record(z.any())));
