// Generated by ts-to-zod
import { z } from 'zod';

import { singleChatTemplateSchema } from './single-chat-template.zod.js';
import { multiChatTemplateSchema } from './multi-chat-template.zod.js';

export const templateSchema = z.union([
  singleChatTemplateSchema,
  multiChatTemplateSchema
]);
