/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */
import type { EmbeddingResult } from './embedding-result.js';
import type { EmbeddingsUsage } from './embeddings-usage.js';
/**
 * The response from request to embedding model following OpenAI specification.
 */
export type EmbeddingsResponse = {
  /**
   * The object type, which is always "list".
   */
  object: 'list';
  /**
   * The list of embeddings generated by the model.
   */
  data: EmbeddingResult[];
  /**
   * The name of the model used to generate the embedding.
   */
  model: string;
  usage: EmbeddingsUsage;
};
