/*
 * Copyright (c) 2026 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */
import type { ChatMessageContent } from './chat-message-content.js';
import type { MessageToolCalls } from './message-tool-calls.js';
import type { ReasoningBlock } from './reasoning-block.js';
/**
 * Representation of the 'AssistantChatMessage' schema.
 */
export type AssistantChatMessage = {
  role: 'assistant';
  content?: ChatMessageContent;
  refusal?: string;
  tool_calls?: MessageToolCalls;
  /**
   * Reasoning content generated by the model. When building multi-turn conversations, include all reasoning blocks from the previous response verbatim to maintain reasoning context.
   *
   */
  reasoning_content?: ReasoningBlock[];
};
