/*
 * Copyright (c) 2026 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */
import type { TextContent } from './text-content.js';
import type { ToolCallChunk } from './tool-call-chunk.js';
/**
 * Representation of the 'ChatDelta' schema.
 */
export type ChatDelta = {
  role?: string;
  /**
   * Delta content from the model. Plain string for most models; Anthropic Claude
   * returns an array of content blocks ({@link TextContent}[]) in streaming chunks.
   */
  content: string | TextContent[];
  /**
   * The refusal message generated by the model.
   */
  refusal?: string;
  tool_calls?: ToolCallChunk[];
} & Record<string, any>;
