/*
 * Copyright (c) 2026 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */

/**
 * A reasoning block containing the model's internal reasoning content. Applicable to models that support reasoning or extended thinking (e.g. Anthropic Claude). When present in a response, pass back verbatim in the next turn's AssistantChatMessage.reasoning_content to maintain reasoning context.
 *
 */
export type ReasoningBlock = {
  /**
   * The reasoning text generated by the model.
   */
  content?: string;
  /**
   * Encrypted signature for redacted reasoning blocks. Treat as opaque; pass back as-is in subsequent turns.
   *
   */
  signature?: string;
};
