/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */

/**
 * Representation of the 'RefusalContent' schema.
 */
export type RefusalContent = {
  type: 'refusal';
  /**
   * The refusal message generated by the model.
   */
  refusal: string;
} & Record<string, any>;
