/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */
import type { ResponseMessageToolCall } from './response-message-tool-call.js';
/**
 * The tool calls generated by the model, such as function calls.
 */
export type ResponseMessageToolCalls = ResponseMessageToolCall[];
