/*
 * Copyright (c) 2026 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */
import type { MessageToolCalls } from './message-tool-calls.js';
import type { ReasoningBlock } from './reasoning-block.js';
/**
 * Representation of the 'ResponseChatMessage' schema.
 */
export type ResponseChatMessage = {
  role: 'assistant';
  content?: string;
  refusal?: string;
  tool_calls?: MessageToolCalls;
  /**
   * Reasoning or thinking content generated by the model before the final response.
   *
   */
  reasoning_content?: ReasoningBlock[];
};
