/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */

/**
 * Usage of tokens in the response
 */
export type TokenUsage = {
  /**
   * Number of tokens in the prompt.
   */
  prompt_tokens: number;
  /**
   * Number of tokens in the generated completion.
   */
  completion_tokens: number;
  /**
   * Total number of tokens used in the request (prompt + completion).
   */
  total_tokens: number;
  /**
   * Details of the prompt tokens.
   */
  prompt_tokens_details?: {
    /**
     * Audio input tokens present in the prompt.
     */
    audio_tokens?: number;
    /**
     * Cached tokens present in the prompt.
     */
    cached_tokens?: number;
  } & Record<string, any>;
  /**
   * Breakdown of tokens used in a completion.
   */
  completion_tokens_details?: {
    /**
     * When using Predicted Outputs, the number of tokens in the
     * prediction that appeared in the completion.
     *
     */
    accepted_prediction_tokens?: number;
    /**
     * Audio input tokens generated by the model.
     */
    audio_tokens?: number;
    /**
     * Tokens generated by the model for reasoning.
     */
    reasoning_tokens?: number;
    /**
     * When using Predicted Outputs, the number of tokens in the prediction that did not appear in the completion. However, like reasoning tokens, these tokens are still counted in the total completion tokens for purposes of billing, output, and context window limits.
     *
     */
    rejected_prediction_tokens?: number;
  } & Record<string, any>;
} & Record<string, any>;
