/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */
import type { AzureOpenAiChatCompletionMessageToolCallChunk } from './chat-completion-message-tool-call-chunk.js';
/**
 * A chat completion delta generated by streamed model responses.
 */
export type AzureOpenAiChatCompletionStreamResponseDelta = {
  /**
   * The contents of the chunk message.
   */
  content?: string | null;
  /**
   * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
   * @deprecated
   */
  function_call?: {
    /**
     * The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
     */
    arguments?: string;
    /**
     * The name of the function to call.
     */
    name?: string;
  } & Record<string, any>;
  tool_calls?: AzureOpenAiChatCompletionMessageToolCallChunk[];
  /**
   * The role of the author of this message.
   */
  role?: 'system' | 'user' | 'assistant' | 'tool';
  /**
   * The refusal message generated by the model.
   */
  refusal?: string | null;
} & Record<string, any>;
