name: 'Fixed version bump'
description: 'Bumps version for fixed packages and the root package.json using changesets.'
inputs:
  majorVersion:
    description: 'When setting a major version this needs to be set to the actual major version to avoid accidental major version bumps.'
outputs:
  version:
    description: 'The new version'
    value: ${{ steps.run.outputs.version }}
runs:
  using: 'composite'
  steps:
    - name: Run changesets-fixed-version-bump
      id: run
      shell: bash
      working-directory: ${{ github.workspace }}/build-packages/changesets-fixed-version-bump
      env:
        INPUT_MAJORVERSION: ${{ inputs.majorVersion }}
      run: node index.ts
