import { HttpResponse } from '@sap-cloud-sdk/http-client';
import { createLogger } from '@sap-cloud-sdk/util';
import {
  CompletionPostResponse,
  TokenUsage
} from './client/api/schema/index.js';

const logger = createLogger({
  package: 'gen-ai-hub',
  messageContext: 'orchestration-response'
});
/**
 * Representation of an Orchestration response.
 */
export class OrchestrationResponse {
  /**
   * Get the typed Completion Post Response.
   */
  public readonly data: CompletionPostResponse;
  constructor(public readonly rawResponse: HttpResponse) {
    this.data = rawResponse.data;
  }

  /**
   * Usage of tokens in the response.
   * @returns Token usage.
   */
  getTokenUsage(): TokenUsage {
    return this.data.orchestration_result.usage;
  }
  /**
   * Reason for stopping the model.
   * @param choiceIndex - The index of the choice to parse.
   * @returns The finish reason.
   */
  getFinishReason(choiceIndex = 0): string | undefined {
    if (!this.validateChoiceIndex(choiceIndex)) {
      return;
    }
    return this.data.orchestration_result.choices[choiceIndex].finish_reason;
  }

  /**
   * Parses the orchestration response and returns the content.
   * @param choiceIndex - The index of the choice to parse.
   * @returns The message content.
   */
  getContent(choiceIndex = 0): string | undefined {
    if (!this.validateChoiceIndex(choiceIndex)) {
      return;
    }
    if (
      this.data.orchestration_result.choices[choiceIndex].message.content ===
        '' &&
      this.data.orchestration_result.choices[choiceIndex].finish_reason ===
        'content_filter'
    ) {
      throw new Error(
        'Content generated by the LLM was filtered by the output filter. Please try again with a different prompt or filter configuration.'
      );
    }
    return this.data.orchestration_result.choices[choiceIndex].message.content;
  }

  private validateChoiceIndex(choiceIndex: number): boolean {
    const choices = this.data.orchestration_result.choices;
    if (choiceIndex < 0 || choiceIndex >= choices.length) {
      logger.error(`${choiceIndex} is not a valid choice index.`);
      return false;
    }
    return true;
  }
}
