import { createLogger } from '@sap-cloud-sdk/util';
import type { HttpResponse } from '@sap-cloud-sdk/http-client';
import type {
  AssistantChatMessage,
  ChatMessage,
  ChatMessages,
  CompletionPostResponse,
  LlmChoice,
  MessageToolCalls,
  ModuleResults,
  TokenUsage,
  Error as OrchestrationError
} from './client/api/schema/index.js';
import type { OrchestrationStream } from './orchestration-stream.js';

const logger = createLogger({
  package: 'orchestration',
  messageContext: 'orchestration-stream-response'
});

/**
 * Orchestration stream response.
 */
export class OrchestrationStreamResponse<T> {
  public _openStream = true;
  public _data: Partial<CompletionPostResponse> = {};
  private _stream: OrchestrationStream<T> | undefined;
  private _rawResponse: HttpResponse | undefined;

  /**
   * @deprecated Since v2.6.0. Provide an HttpResponse parameter when constructing OrchestrationStreamResponse. This constructor overload will be removed in v3.0.0.
   * Creates an orchestration stream response.
   */
  constructor();

  /**
   * Creates an orchestration stream response.
   * @param rawResponse - The raw HTTP response from the orchestration service. SSE data is not part of the immediate response.
   */
  // eslint-disable-next-line @typescript-eslint/unified-signatures
  constructor(rawResponse: HttpResponse);

  constructor(rawResponse?: HttpResponse) {
    if (!rawResponse) {
      logger.warn(
        'Constructing OrchestrationStreamResponse without raw HTTP response is deprecated and can lead to runtime errors when accessing `rawResponse`.'
      );
      return;
    }
    this._rawResponse = rawResponse;
  }

  /**
   * Gets the raw HTTP response from the orchestration service. SSE data is not part of the immediate response.
   * @returns The raw HTTP response.
   * @throws {Error} When OrchestrationStreamResponse was constructed without a raw response parameter (deprecated).
   */
  get rawResponse(): HttpResponse {
    if (!this._rawResponse) {
      throw new Error(
        'The raw response is not available. Please provide the raw response when constructing `OrchestrationStreamResponse`'
      );
    }
    return this._rawResponse;
  }

  /**
   * Gets the token usage for the response.
   * @returns The token usage for the response.
   */
  getTokenUsage(): TokenUsage | undefined {
    if (this.isStreamOpen()) {
      return;
    }
    return this._data.final_result?.usage;
  }

  /**
   * Gets the request ID for the stream response.
   * @returns The request ID, or undefined if the first chunk has not been received yet.
   */
  getRequestId(): string | undefined {
    return this._data.request_id;
  }

  /**
   * Gets the finish reason for a specific choice index.
   * @param choiceIndex - The index of the choice to get the finish reason for.
   * @returns The finish reason for the specified choice index.
   */
  getFinishReason(choiceIndex = 0): string | undefined {
    if (this.isStreamOpen()) {
      return;
    }
    return this.findChoiceByIndex(choiceIndex)?.finish_reason;
  }

  /**
   * Parses the orchestration response and returns the content.
   * If the response was filtered, an error is thrown.
   * @param choiceIndex - The index of the choice to parse.
   * @returns The message content.
   */
  getContent(choiceIndex = 0): string | undefined {
    if (this.isStreamOpen()) {
      return;
    }
    const choice = this.findChoiceByIndex(choiceIndex);
    return choice?.message?.content;
  }

  /**
   * Parses the orchestration response and returns the tool calls generated by the model.
   * @param choiceIndex - The index of the choice to parse.
   * @returns The message tool calls.
   */
  getToolCalls(choiceIndex = 0): MessageToolCalls | undefined {
    if (this.isStreamOpen()) {
      return;
    }
    const choice = this.findChoiceByIndex(choiceIndex);
    return choice?.message?.tool_calls;
  }

  /**
   * Parses the orchestration response and returns the refusal message generated by the model.
   * @param choiceIndex - The index of the choice to parse.
   * @returns The refusal string.
   */
  getRefusal(choiceIndex = 0): string | undefined {
    if (this.isStreamOpen()) {
      return;
    }
    const choice = this.findChoiceByIndex(choiceIndex);
    return choice?.message?.refusal;
  }

  /**
   * Messages that can be used for subsequent prompts as message history.
   * @param choiceIndex - The index of the choice to parse.
   * @returns A list of all messages.
   */
  getAllMessages(choiceIndex = 0): ChatMessages | undefined {
    if (this.isStreamOpen()) {
      return;
    }
    const messages: ChatMessage[] =
      this._data.intermediate_results?.templating ?? [];
    const content = this.findChoiceByIndex(choiceIndex)?.message;
    return content ? [...messages, content] : messages;
  }

  /**
   * Gets the assistant message from the response.
   * @param choiceIndex - The index of the choice to use (default is 0).
   * @returns The assistant message.
   */
  getAssistantMessage(choiceIndex = 0): AssistantChatMessage | undefined {
    if (this.isStreamOpen()) {
      return;
    }
    return this.findChoiceByIndex(choiceIndex)?.message;
  }

  /**
   * Gets the intermediate results from the orchestration response.
   * @returns The intermediate results.
   */
  getIntermediateResults(): ModuleResults | undefined {
    if (this.isStreamOpen()) {
      return;
    }
    return this._data.intermediate_results;
  }

  /**
   * Gets the intermediate failures from the orchestration response.
   * When using module fallback, this contains errors from module configurations
   * that failed before a successful one was found.
   * @returns The intermediate failures, or undefined if there were none.
   */
  getIntermediateFailures(): OrchestrationError[] | undefined {
    if (this.isStreamOpen()) {
      return;
    }
    return this._data.intermediate_failures;
  }

  /**
   * Parses the response and returns the choice by index.
   * @param index - The index of the choice to find.
   * @returns An {@link LLMChoice} object associated with the index.
   */
  findChoiceByIndex(index: number): LlmChoice | undefined {
    if (this.isStreamOpen()) {
      return;
    }
    return this.getChoices().find((c: { index: number }) => c.index === index);
  }

  get stream(): OrchestrationStream<T> {
    if (!this._stream) {
      throw new Error('Response stream is undefined.');
    }
    return this._stream;
  }

  private getChoices() {
    return this._data.final_result?.choices ?? [];
  }

  private isStreamOpen(): boolean {
    if (this._openStream) {
      throw Error(
        'The stream is still open, the requested data is not available yet. Please wait until the stream is closed.'
      );
    }
    return this._openStream;
  }

  /**
   * @internal
   */
  set stream(stream: OrchestrationStream<T>) {
    this._stream = stream;
  }
}
