name: auto fix lint

on:
  pull_request:
    branches:
      - main

jobs:
  fix-lint:
    if: github.actor != 'dependabot[bot]' && !github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.SAP_AI_SDK_BOT_CLIENT_ID }}
          private-key: ${{ secrets.SAP_AI_SDK_BOT_PRIVATE_KEY }}
          permission-contents: write
      - uses: sap/ai-sdk-js/.github/actions/setup@main
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}
      - run: pnpm lint:fix
      - name: Commit Changes if needed
        run: |
          diff=`git diff`
          if [ ! -z "$diff" ]; then
            git config --global user.email "${{ vars.SAP_AI_SDK_BOT_EMAIL }}"
            git config --global user.name "${{ vars.SAP_AI_SDK_BOT_NAME }}"
            git commit -m "fix: Changes from lint" -a
            git push
          fi
