name: auto generate

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  generate:
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' && github.repository == github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.SAP_AI_SDK_BOT_CLIENT_ID }}
          private-key: ${{ secrets.SAP_AI_SDK_BOT_PRIVATE_KEY }}
          permission-contents: write
      - uses: sap/cloud-sdk-js/.github/actions/setup@0b9bf8e65a8294c108b981788751ea34129d3fa4 # main
        with:
          ref: ${{ github.head_ref }}
          registry-token: ${{ secrets.NPM_TOKEN_ARTIFACTORY }}
          persist-credentials: true
          token: ${{ steps.app-token.outputs.token }}
      - name: Generate and apply patches
        run: |
          pnpm generate
          pnpm apply-patches
      - name: Commit Changes if needed
        env:
          BOT_EMAIL: ${{ vars.SAP_AI_SDK_BOT_EMAIL }}
          BOT_NAME: ${{ vars.SAP_AI_SDK_BOT_NAME }}
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.email "$BOT_EMAIL"
            git config --global user.name "$BOT_NAME"
            git add -A
            git commit -m "fix: Changes from generation"
            git push
          fi
