name: build

on:
  push:
    branches: ['main']
  pull_request: ~
  workflow_dispatch: ~

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJSON(vars.SUPPORTED_NODE_VERSIONS) }}

    steps:
      - uses: sap/ai-sdk-js/.github/actions/setup@scripts
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm i --frozen-lockfile
      - run: pnpm test:unit
      - run: pnpm test:type

  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: sap/ai-sdk-js/.github/actions/setup@scripts
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v4
      - run: pnpm i --frozen-lockfile
      # - run: pnpm build # might be needed in the future
      - run: pnpm lint
      - run: pnpm compile:cjs
      - run: pnpm check:public-api
        name: Check public api

  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    needs: [test, checks]
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.6
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
