name: documentation

on:
  pull_request:
    branches:
      - main

jobs:
  grammar-check:
    runs-on: ubuntu-latest
    steps:
      - name: Vale
        # vale fails if the PR is too large, e.g. when updating API docs
        if: ${{ github.event.pull_request.changed_files < 100 }}
        # You may pin to the exact commit or the version.
        # uses: errata-ai/vale-action@0da98680790f89b8d5b685de9c264f55addc971b
        uses: errata-ai/vale-action@reviewdog
        with:
          # version of 'vale' to use
          # see https://github.com/errata-ai/vale for all releases
          version: 3.7.1
          # changed files. computed in the step above
          files: ${{ steps.changed-files.outputs.CHANGED_FILES }}
          # the separator for the file list. we are using a comma (see step above)
          separator: ","
          # let review dog fail if there are errors
          fail_on_error: true
        env:
          # Required
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
