name: draft-release

on:
  push:
    tags: ['v*']

jobs:
  draft-github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: sap/cloud-sdk-js/.github/actions/setup@main
        with:
          registry-token: ${{ secrets.NPM_TOKEN_ARTIFACTORY }}
      - name: Get Changelog
        id: get-changelog
        uses: sap/cloud-sdk-js/.github/actions/get-changelog@main
      - name: Create Draft Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: ${{ steps.get-changelog.outputs.changelog }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          gh release create "$REF_NAME" \
            --title "$REF_NAME" \
            --verify-tag \
            --notes "$CHANGELOG" \
            --draft
