name: draft-release

on:
  push:
    tags: ['v*']

jobs:
  draft-github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: sap/cloud-sdk-js/.github/actions/setup@pnpm-setup
        with:
          registry-token: ${{ secrets.NPM_TOKEN_ARTIFACTORY }}
      - name: Get Changelog
        uses: sap/cloud-sdk-js/.github/actions/get-changelog@main
        id: get-changelog
      - uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          body: ${{ steps.get-changelog.outputs.changelog }}
