name: e2e tests

on:
  workflow_dispatch:
  schedule:
    - cron: 0 22 * * *

permissions: {}

jobs:
  e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        environment: [staging, production]
        # disabled, because currently staging is behind production
        exclude:
          - environment: staging
        include:
          - environment: production
            secret-name: AI_CORE_PRODUCTION
    name: 'Build and Test'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: sap/cloud-sdk-js/.github/actions/setup@main
      - name: Create .env file
        env:
          AICORE_SERVICE_KEY: ${{ secrets[matrix.secret-name] }} # zizmor: ignore[overprovisioned-secrets]
        run: |
          echo "AICORE_SERVICE_KEY='$AICORE_SERVICE_KEY'" > sample-code/.env
          echo "AICORE_SERVICE_KEY='$AICORE_SERVICE_KEY'" > tests/e2e-tests/.env
          url=$(echo "$AICORE_SERVICE_KEY" | jq -r '.serviceurls.AI_API_URL' | sed 's|^https://||')
          echo "Using AI Core ${{ matrix.environment }} instance on $url"
      - name: 'Start Sample App'
        id: sample-app
        working-directory: ./sample-code
        # TODO: use background: true
        shell: bash
        run: |
          pnpm local &
          JOB_ID=$!
          echo "JOB_ID=$JOB_ID" >> "$GITHUB_OUTPUT"
      - name: 'Wait For Sample App To Be Ready'
        working-directory: ./sample-code
        run: |
          timeout=15
          while ! nc -z localhost 8080; do
            sleep 1
            timeout=$((timeout - 1))
            if [ $timeout -le 0 ]; then
              echo "Server did not start within 15 seconds."
              exit 1
            fi
          done
          wget -qO- -S --content-on-error localhost:8080
      - name: 'Execute E2E Tests'
        run: pnpm test:e2e
      - name: 'Stop Sample App'
        if: always() && env.JOB_ID != ''
        # TODO: use cancel: sample-app
        # cancel: sample-app
        env:
          JOB_ID: ${{ steps.sample-app.outputs.JOB_ID }}
        run: |
          echo "Stopping Sample App with PID $JOB_ID"
          kill -TERM "$JOB_ID" 2>/dev/null || true
          timeout 10 tail --pid="$JOB_ID" -f /dev/null 2>/dev/null || kill -KILL "$JOB_ID" 2>/dev/null || true
      - name: 'Slack Notification'
        if: failure() && github.event_name == 'schedule'
        uses: slackapi/slack-github-action@0d95c9a7becc1e6e297d76df9bc735c44f4cbcbc # v3.0.5
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            {
              "username": "GitHub E2E Test Runner",
              "text": "⚠️ E2E Test for v2 Failed! 😬 Please inspect & fix by clicking <https://github.com/SAP/ai-sdk-js/actions/runs/${{ github.run_id }}|here>"
            }
