name: transitive dependency update

on:
  schedule:
    - cron: '0 2 1 * *' # Runs at 02:00 UTC on the 1st of every month
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ secrets.SAP_AI_SDK_BOT_CLIENT_ID }}
          private-key: ${{ secrets.SAP_AI_SDK_BOT_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
      - name: Setup Environment
        uses: sap/cloud-sdk-js/.github/actions/setup@main
        with:
          registry-token: ${{ secrets.NPM_TOKEN_ARTIFACTORY }}
          persist-credentials: 'true'
          token: ${{ steps.app-token.outputs.token }}
          skip-install: 'true'

      - name: Update Transitive Dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_ARTIFACTORY }}
        run: |
          pnpm --no-save update --recursive
          pnpm audit --audit-level high

      - name: Check for Changes
        id: check-changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "has-changes=true" >> $GITHUB_OUTPUT
          else
            echo "has-changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push
        id: commit
        if: steps.check-changes.outputs.has-changes == 'true'
        env:
          BOT_EMAIL: ${{ vars.SAP_AI_SDK_BOT_EMAIL }}
          BOT_NAME: ${{ vars.SAP_AI_SDK_BOT_NAME }}
        run: |
          git config --global user.email "$BOT_EMAIL"
          git config --global user.name "$BOT_NAME"
          BRANCH_NAME="bot/monthly-transitive-dependency-update-$(date -u +%Y%m%d-%H%M%S)"
          git checkout -b "$BRANCH_NAME"
          git add pnpm-lock.yaml
          git commit -m "chore: update pnpm transitive dependencies"
          git push --set-upstream origin "$BRANCH_NAME"
          echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.check-changes.outputs.has-changes == 'true'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh pr create \
            --title "chore: Monthly Transitive Dependency Update" \
            --body "This is an automated PR to update pnpm transitive dependencies." \
            --base main \
            --head "${{ steps.commit.outputs.branch-name }}"

      - name: Enable auto-merge
        if: steps.check-changes.outputs.has-changes == 'true'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh pr merge --auto --squash "${{ steps.commit.outputs.branch-name }}"
