name: publish-next

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  e2e-tests:
    name: 'Run E2E Tests'
    uses: ./.github/workflows/e2e-tests.yaml
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    needs: [e2e-tests]

    steps:
      - uses: sap/ai-sdk-js/.github/actions/setup@main
        with:
          pnpm-install-args: ''

      - name: prepare canary changeset
        run: |
          rm -f .changeset/*.md || true
          cat <<EOT >> .changeset/canary-release-changeset.md
          ---
          '@sap-ai-sdk/core': patch
          ---

          Canary release
          EOT

      - name: publish
        run: |
          date=`date +%Y%m%d%H%M%S`
          pnpm changeset pre enter ${date}
          pnpm changeset version
          pnpm changeset pre exit
          pnpm changeset publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
