name: publish-canary

on:
  workflow_call:
    inputs:
      tag:
        description: 'Dist tag for the release. If you chose something different than "canary", make sure to delete it once it is not needed anymore.'
        type: string
        required: false
        default: 'canary'

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: sap/cloud-sdk-js/.github/actions/setup@main
        with:
          node-version: 24 # Will install npm 11 needed for trusted publishing
          pnpm-install-args: ''
          package-manager-cache: false
          registry-url: 'https://registry.npmjs.org'

      - name: prepare canary changeset
        run: |
          rm -f .changeset/*.md || true
          cat <<EOT >> .changeset/canary-release-changeset.md
          ---
          '@sap-ai-sdk/core': patch
          ---

          Canary release
          EOT

      - name: publish
        env:
          INPUTS_TAG: ${{ inputs.tag }}
        run: |
          date=`date +%Y%m%d%H%M%S`
          pnpm changeset pre enter "${date}"
          pnpm changeset version
          pnpm changeset pre exit
          pnpm changeset publish --tag "${INPUTS_TAG}"
      - name: Notify Slack on failure
        if: ${{ github.event_name == 'schedule' && (failure() || cancelled()) }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: AI SDK Pipeline Bot
          SLACK_TITLE: 'Canary Release Failed for ${{ job.status }}'
          SLACK_MESSAGE: 'Canary release failed for ${{ github.repository }} (ref: ${{ github.ref_name }}).'
          MSG_MINIMAL: event,actions url
          SLACK_COLOR: ${{ job.status }}
          SLACK_MSG_AUTHOR: ''
          SLACK_ICON: https://sap.github.io/ai-sdk/img/AI-SDK-Logo.svg
        uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2.4.0
